### ISSUE TITLE
Add a version tag

### ISSUE THREAD

**Issue by martinrybak** [n-b/UIView-NibLoading#4]
Great library! Solved a big pain point of mine. I would love to publish a CocoaPods podspec for this, but you need to add a tag to your repo, such as 1.0.0. Thanks!

**Comment by n-b** [comment]
@martinrybak Thanks! [Here's the 1.0.0 tag](https://github.com/n-b/UIView-NibLoading/tree/1.0.0). I don't use Cocoapods myself (long story short: I don't need it on the long-term project I'm working on.) but I'll gladly accept a pr for a podspec.

**Comment by martinrybak** [comment]
Thanks!

**Comment by martinrybak** [comment]
Here ya go! Thanks again for a great library. When you update, please remember to tag each release in GitHub. If the release is backwards compatible, just increment the patch number, i.e. 1.0.1, 1.0.2. If not, increment the minor or major version number, i.e. 1.1.0, 2.0.0. This will keep it in line with CocoaPods' dependency management practices.

pod 'UIView+NibLoading', '~> 1.0.0'

http://cocoapods.org/?q=nib%20loading
